"""Build paper/fv/numbers.tex and paper/fv/numbers.json from every src/fv/num_*.py part.

Each part module defines `macros()` returning a list of dicts made with fv_numlib.macro(). This script
imports every part, rejects duplicate or malformed names, and writes the two files. It never edits a part.
Run:  python src/fv/fv_numbers.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import einv_paths as EINV
import glob
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from fv_numlib import NAME_RE  # noqa: E402

PAPER = (EINV.V2 + "/paper/fv")


def main():
    allm, owner = [], {}
    for path in sorted(glob.glob(os.path.join(HERE, "num_*.py"))):
        mod_name = os.path.splitext(os.path.basename(path))[0]
        spec = importlib.util.spec_from_file_location(mod_name, path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        for m in mod.macros():
            assert NAME_RE.match(m["name"]), (mod_name, m["name"])
            if m["name"] in owner:
                raise SystemExit(f"duplicate macro {m['name']} in {mod_name} and {owner[m['name']]}")
            owner[m["name"]] = mod_name
            m["part"] = mod_name
            allm.append(m)
    lines = ["% GENERATED by src/fv/fv_numbers.py from the result files. Do not edit by hand.",
             f"% {len(allm)} macros. Sources and key paths: numbers.json.", ""]
    part = None
    for m in allm:
        if m["part"] != part:
            part = m["part"]
            lines += ["", f"% ---- {part}"]
        lines.append(f"\\newcommand{{\\{m['name']}}}{{{m['text']}}}"
                     f"  % {os.path.basename(str(m['source']))} :: {m['key']} [E{m['entry']}]")
    with open(os.path.join(PAPER, "numbers.tex"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    with open(os.path.join(PAPER, "numbers.json"), "w", encoding="utf-8") as f:
        json.dump({m["name"]: {k: v for k, v in m.items() if k != "name"} for m in allm}, f, indent=1,
                  default=float)
    print(f"numbers.tex: {len(allm)} macros from {len(set(owner.values()))} parts")


if __name__ == "__main__":
    main()
